import { Module } from '@nestjs/common'
import { JwtModule } from '@nestjs/jwt'
import { ConfigModule } from '@nestjs/config'
import { PrismaModule } from '../prisma/prisma.module'
import { PrismaService } from '../prisma/prisma.service'
import { MinioModule } from './minio.module'
import {
  PrismaUnitOfWork,
  PrismaUserRepository,
  PrismaRoleRepository,
  PrismaPermissionRepository,
  PrismaStudentRepository,
  PrismaStudentPointLogRepository,
  PrismaEmailVerificationTokenRepository,
  PrismaAdminRepository,
  PrismaResetPasswordTokenRepository,
  PrismaZaloTokenRepository,
  PrismaMediaRepository,
  PrismaAdminLogRepository,
  PrismaMediaFolderRepository,
  PrismaMediaUsageRepository,
  PrismaSeoMediaSlotRepository,
  PrismaSeoMediaItemRepository,
  PrismaCourseRepository,
  PrismaCourseClassRepository,
  PrismaLessonRepository,
  PrismaLearningItemRepository,
  PrismaStudentLearningItemRepository,
  PrismaLessonLearningItemRepository,
  PrismaClassSessionRepository,
  PrismaClassStudentRepository,
  PrismaCourseEnrollmentRepository,
  PrismaAttendanceRepository,
  PrismaNotificationRepository,
  PrismaBackgroundJobRepository,
  PrismaBackgroundJobRunRepository,
  PrismaBackgroundJobLockRepository,
  PrismaSepayTransactionSyncCursorRepository,
  PrismaTuitionPaymentRepository,
  PrismaReceivingBankAccountRepository,
  PrismaTuitionGradeReceivingBankAccountRepository,
  PrismaTuitionCollectionConfigurationRepository,
  PrismaPaymentIntentRepository,
  PrismaPaymentAttemptRepository,
  PrismaBankTransferTransactionRepository,
  PrismaTempExamRepository,
  PrismaTempSectionRepository,
  PrismaTempQuestionRepository,
  PrismaTempStatementRepository,
  PrismaTempQuestionChapterRepository,
  PrismaExamImportSessionRepository,
  PrismaExamRepository,
  PrismaExamAttemptRepository,
  PrismaCompetitionRepository,
  PrismaCompetitionSubmitRepository,
  PrismaCompetitionAnswerRepository,
  PrismaSectionRepository,
  PrismaQuestionRepository,
  PrismaQuestionAnswerRepository,
  PrismaStatementRepository,
  PrismaQuestionExamRepository,
  PrismaQuestionChapterRepository,
  PrismaDocumentContentRepository,
  PrismaVideoContentRepository,
  PrismaYoutubeContentRepository,
  PrismaHomeworkContentRepository,
  PrismaHomeworkSubmitRepository,
  PrismaQuestionChatMessageRepository,
  PrismaQuestionChatRepository,
  PrismaDocumentRepository,
  PrismaTeacherProfileRepository,
  PrismaDocumentTagRepository,
  PrismaTagRepository,
  PrismaOnlineCourseInvoiceRepository,
  PrismaOnlineCourseInvoiceItemRepository,
  PrismaOnlineCoursePaymentAttemptRepository,
  PrismaAchievementBoardRepository,
  PrismaNewsArticleRepository,
  PrismaReportRepository,
  PrismaAssistantShiftSeriesRepository,
  PrismaAssistantShiftRepository,
  PrismaAssistantShiftAssignmentRepository,
} from './repositories'
import {
  PasswordService,
  JwtTokenService,
  TokenHashService,
  TokenService,
  HttpClientService,
  AuthService,
  ResendEmailService,
  ZaloService,
  // SupabaseStorageService, // Disabled: not using Supabase anymore
  MediaProcessingService,
  DocumentThumbnailService,
  DocumentContentExtractionService,
  DocumentSeoAiService,
  TeacherProfileSeoAiService,
  AchievementBoardSeoAiService,
  NewsArticleSeoAiService,
  DocumentMediaAltTextAiService,
  ExcelService,
} from './services'
import { ImageExportService } from './services/image-export.service'
import { MistralService } from './services/mistral.service'
import { OpenAIService } from './services/openai.service'
import { CompetitionSubmitFeedbackAiService } from './services/competition-submit-feedback-ai.service'
import { ExamSplitService } from './services/exam-split.service'
import { MarkdownFixService } from './services/markdown-fix.service'
import { MarkdownRenderService } from './services/markdown-render.service'
import { QuestionChapterClassificationService } from './services/question-chapter-classification.service'
import { FileConverterService } from './services/file-converter.service'
import { QuestionChatAIService } from './services/question-chat-ai.service'
import { VnpayService } from './services/vnpay.service'
import { PayosService } from './services/payos.service'
import { SepayService } from './services/sepay.service'
import { GoogleAdminStrategy } from './strategies/google-admin.strategy'
import { GoogleStudentStrategy } from './strategies/google-student.strategy'
import jwtConfig from '../config/jwt.config'
import googleOAuthConfig from '../config/google-oauth.config'
import emailConfig from '../config/email.config'
import httpClientConfig from '../config/http-client.config'
import supabaseConfig from '../config/supabase.config'
import mistralConfig from '../config/mistral.config'
import openaiConfig from '../config/openai.config'
import payosConfig from '../config/payos.config'
import sepayConfig from '../config/sepay.config'
import {
  AchievementBoardSeoAiService as AchievementBoardSeoAiServicePort,
  AuthService as AuthServicePort,
  CompetitionSubmitFeedbackAiService as CompetitionSubmitFeedbackAiServicePort,
  DocumentContentExtractionService as DocumentContentExtractionServicePort,
  DocumentMediaAltTextAiService as DocumentMediaAltTextAiServicePort,
  DocumentSeoAiService as DocumentSeoAiServicePort,
  DocumentThumbnailService as DocumentThumbnailServicePort,
  ExamSplitService as ExamSplitServicePort,
  ExcelService as ExcelServicePort,
  FileConverterService as FileConverterServicePort,
  HttpClientService as HttpClientServicePort,
  ImageExportService as ImageExportServicePort,
  JwtTokenService as JwtTokenServicePort,
  MarkdownFixService as MarkdownFixServicePort,
  MarkdownRenderService as MarkdownRenderServicePort,
  MediaProcessingService as MediaProcessingServicePort,
  MistralService as MistralServicePort,
  NewsArticleSeoAiService as NewsArticleSeoAiServicePort,
  PasswordService as PasswordServicePort,
  PayosService as PayosServicePort,
  SepayService as SepayServicePort,
  QuestionChapterClassificationService as QuestionChapterClassificationServicePort,
  QuestionChatAIService as QuestionChatAIServicePort,
  TeacherProfileSeoAiService as TeacherProfileSeoAiServicePort,
  TokenHashService as TokenHashServicePort,
  TokenService as TokenServicePort,
  VnpayService as VnpayServicePort,
  ZaloService as ZaloServicePort,
} from 'src/application/interfaces'

@Module({
  imports: [
    PrismaModule,
    MinioModule,
    ConfigModule.forFeature(jwtConfig),
    ConfigModule.forFeature(googleOAuthConfig),
    ConfigModule.forFeature(emailConfig),
    ConfigModule.forFeature(httpClientConfig),
    ConfigModule.forFeature(mistralConfig),
    ConfigModule.forFeature(openaiConfig),
    ConfigModule.forFeature(payosConfig),
    ConfigModule.forFeature(sepayConfig),
    // ConfigModule.forFeature(supabaseConfig), // Disabled: not using Supabase anymore
    JwtModule.register({}), // Empty config, sẽ override trong service
  ],
  providers: [
    { provide: AchievementBoardSeoAiServicePort, useExisting: AchievementBoardSeoAiService },
    { provide: AuthServicePort, useExisting: 'AUTH_SERVICE' },
    { provide: CompetitionSubmitFeedbackAiServicePort, useExisting: CompetitionSubmitFeedbackAiService },
    { provide: DocumentContentExtractionServicePort, useExisting: DocumentContentExtractionService },
    { provide: DocumentMediaAltTextAiServicePort, useExisting: DocumentMediaAltTextAiService },
    { provide: DocumentSeoAiServicePort, useExisting: DocumentSeoAiService },
    { provide: DocumentThumbnailServicePort, useExisting: DocumentThumbnailService },
    { provide: ExamSplitServicePort, useExisting: ExamSplitService },
    { provide: ExcelServicePort, useExisting: ExcelService },
    { provide: FileConverterServicePort, useExisting: FileConverterService },
    { provide: HttpClientServicePort, useExisting: 'HTTP_CLIENT_SERVICE' },
    { provide: ImageExportServicePort, useExisting: ImageExportService },
    { provide: JwtTokenServicePort, useExisting: 'JWT_TOKEN_SERVICE' },
    { provide: MarkdownFixServicePort, useExisting: MarkdownFixService },
    { provide: MarkdownRenderServicePort, useExisting: MarkdownRenderService },
    { provide: MediaProcessingServicePort, useExisting: MediaProcessingService },
    { provide: MistralServicePort, useExisting: MistralService },
    { provide: NewsArticleSeoAiServicePort, useExisting: NewsArticleSeoAiService },
    { provide: PasswordServicePort, useExisting: 'PASSWORD_SERVICE' },
    { provide: PayosServicePort, useExisting: PayosService },
    { provide: SepayServicePort, useExisting: SepayService },
    { provide: QuestionChapterClassificationServicePort, useExisting: QuestionChapterClassificationService },
    { provide: QuestionChatAIServicePort, useExisting: QuestionChatAIService },
    { provide: TeacherProfileSeoAiServicePort, useExisting: TeacherProfileSeoAiService },
    { provide: TokenHashServicePort, useExisting: 'TOKEN_HASH_SERVICE' },
    { provide: TokenServicePort, useExisting: TokenService },
    { provide: VnpayServicePort, useExisting: VnpayService },
    { provide: ZaloServicePort, useExisting: ZaloService },
    {
      provide: 'UNIT_OF_WORK',
      useClass: PrismaUnitOfWork,
    },
    {
      provide: 'IUserRepository',
      useFactory: (prisma: PrismaService) => new PrismaUserRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IAdminRepository',
      useFactory: (prisma: PrismaService) => new PrismaAdminRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IRoleRepository',
      useFactory: (prisma: PrismaService) => new PrismaRoleRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IPermissionRepository',
      useFactory: (prisma: PrismaService) => new PrismaPermissionRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IStudentRepository',
      useFactory: (prisma: PrismaService) => new PrismaStudentRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IEmailVerificationTokenRepository',
      useFactory: (prisma: PrismaService) => new PrismaEmailVerificationTokenRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IPasswordResetTokenRepository',
      useFactory: (prisma: PrismaService) => new PrismaResetPasswordTokenRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IZaloTokenRepository',
      useFactory: (prisma: PrismaService) => new PrismaZaloTokenRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IMediaRepository',
      useFactory: (prisma: PrismaService) => new PrismaMediaRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IMediaFolderRepository',
      useFactory: (prisma: PrismaService) => new PrismaMediaFolderRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IMediaUsageRepository',
      useFactory: (prisma: PrismaService) => new PrismaMediaUsageRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ISeoMediaSlotRepository',
      useFactory: (prisma: PrismaService) => new PrismaSeoMediaSlotRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ISeoMediaItemRepository',
      useFactory: (prisma: PrismaService) => new PrismaSeoMediaItemRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IAdminAuditLogRepository',
      useFactory: (prisma: PrismaService) => new PrismaAdminLogRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IBackgroundJobRepository',
      useFactory: (prisma: PrismaService) => new PrismaBackgroundJobRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IBackgroundJobRunRepository',
      useFactory: (prisma: PrismaService) => new PrismaBackgroundJobRunRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IBackgroundJobLockRepository',
      useFactory: (prisma: PrismaService) => new PrismaBackgroundJobLockRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ISepayTransactionSyncCursorRepository',
      useFactory: (prisma: PrismaService) => new PrismaSepayTransactionSyncCursorRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ICourseRepository',
      useFactory: (prisma: PrismaService) => new PrismaCourseRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ICourseClassRepository',
      useFactory: (prisma: PrismaService) => new PrismaCourseClassRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ILessonRepository',
      useFactory: (prisma: PrismaService) => new PrismaLessonRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ILearningItemRepository',
      useFactory: (prisma: PrismaService) => new PrismaLearningItemRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IStudentLearningItemRepository',
      useFactory: (prisma: PrismaService) => new PrismaStudentLearningItemRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ILessonLearningItemRepository',
      useFactory: (prisma: PrismaService) => new PrismaLessonLearningItemRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IClassSessionRepository',
      useFactory: (prisma: PrismaService) => new PrismaClassSessionRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IClassStudentRepository',
      useFactory: (prisma: PrismaService) => new PrismaClassStudentRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ICourseEnrollmentRepository',
      useFactory: (prisma: PrismaService) => new PrismaCourseEnrollmentRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IAttendanceRepository',
      useFactory: (prisma: PrismaService) => new PrismaAttendanceRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'INotificationRepository',
      useFactory: (prisma: PrismaService) => new PrismaNotificationRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ITuitionPaymentRepository',
      useFactory: (prisma: PrismaService) => new PrismaTuitionPaymentRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IReceivingBankAccountRepository',
      useFactory: (prisma: PrismaService) => new PrismaReceivingBankAccountRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ITuitionGradeReceivingBankAccountRepository',
      useFactory: (prisma: PrismaService) => new PrismaTuitionGradeReceivingBankAccountRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ITuitionCollectionConfigurationRepository',
      useFactory: (prisma: PrismaService) => new PrismaTuitionCollectionConfigurationRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IPaymentIntentRepository',
      useFactory: (prisma: PrismaService) => new PrismaPaymentIntentRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IPaymentAttemptRepository',
      useFactory: (prisma: PrismaService) => new PrismaPaymentAttemptRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IBankTransferTransactionRepository',
      useFactory: (prisma: PrismaService) => new PrismaBankTransferTransactionRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ITempExamRepository',
      useFactory: (prisma: PrismaService) => new PrismaTempExamRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ITempSectionRepository',
      useFactory: (prisma: PrismaService) => new PrismaTempSectionRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ITempQuestionRepository',
      useFactory: (prisma: PrismaService) => new PrismaTempQuestionRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ITempStatementRepository',
      useFactory: (prisma: PrismaService) => new PrismaTempStatementRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ITempQuestionChapterRepository',
      useFactory: (prisma: PrismaService) => new PrismaTempQuestionChapterRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IExamImportSessionRepository',
      useFactory: (prisma: PrismaService) => new PrismaExamImportSessionRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IExamRepository',
      useFactory: (prisma: PrismaService) => new PrismaExamRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IExamAttemptRepository',
      useFactory: (prisma: PrismaService) => new PrismaExamAttemptRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ICompetitionRepository',
      useFactory: (prisma: PrismaService) => new PrismaCompetitionRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ICompetitionSubmitRepository',
      useFactory: (prisma: PrismaService) => new PrismaCompetitionSubmitRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ICompetitionAnswerRepository',
      useFactory: (prisma: PrismaService) => new PrismaCompetitionAnswerRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ISectionRepository',
      useFactory: (prisma: PrismaService) => new PrismaSectionRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ISectionRepository',
      useFactory: (prisma: PrismaService) => new PrismaSectionRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IQuestionRepository',
      useFactory: (prisma: PrismaService) => new PrismaQuestionRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IQuestionAnswerRepository',
      useFactory: (prisma: PrismaService) => new PrismaQuestionAnswerRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IStatementRepository',
      useFactory: (prisma: PrismaService) => new PrismaStatementRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IQuestionExamRepository',
      useFactory: (prisma: PrismaService) => new PrismaQuestionExamRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IQuestionChapterRepository',
      useFactory: (prisma: PrismaService) => new PrismaQuestionChapterRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IDocumentContentRepository',
      useFactory: (prisma: PrismaService) => new PrismaDocumentContentRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IVideoContentRepository',
      useFactory: (prisma: PrismaService) => new PrismaVideoContentRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IYoutubeContentRepository',
      useFactory: (prisma: PrismaService) => new PrismaYoutubeContentRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IHomeworkContentRepository',
      useFactory: (prisma: PrismaService) => new PrismaHomeworkContentRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IHomeworkSubmitRepository',
      useFactory: (prisma: PrismaService) => new PrismaHomeworkSubmitRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IStudentRepository',
      useFactory: (prisma: PrismaService) => new PrismaStudentRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IQuestionChatMessageRepository',
      useFactory: (prisma: PrismaService) => new PrismaQuestionChatMessageRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IQuestionChatRepository',
      useFactory: (prisma: PrismaService) => new PrismaQuestionChatRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IDocumentRepository',
      useFactory: (prisma: PrismaService) => new PrismaDocumentRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ITeacherProfileRepository',
      useFactory: (prisma: PrismaService) => new PrismaTeacherProfileRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'ITagRepository',
      useFactory: (prisma: PrismaService) => new PrismaTagRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IDocumentTagRepository',
      useFactory: (prisma: PrismaService) => new PrismaDocumentTagRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IOnlineCourseInvoiceRepository',
      useFactory: (prisma: PrismaService) => new PrismaOnlineCourseInvoiceRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IOnlineCourseInvoiceItemRepository',
      useFactory: (prisma: PrismaService) => new PrismaOnlineCourseInvoiceItemRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IOnlineCoursePaymentAttemptRepository',
      useFactory: (prisma: PrismaService) => new PrismaOnlineCoursePaymentAttemptRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IStudentPointLogRepository',
      useFactory: (prisma: PrismaService) => new PrismaStudentPointLogRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IAchievementBoardRepository',
      useFactory: (prisma: PrismaService) => new PrismaAchievementBoardRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'INewsArticleRepository',
      useFactory: (prisma: PrismaService) => new PrismaNewsArticleRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IReportRepository',
      useFactory: (prisma: PrismaService) => new PrismaReportRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IAssistantShiftSeriesRepository',
      useFactory: (prisma: PrismaService) => new PrismaAssistantShiftSeriesRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IAssistantShiftRepository',
      useFactory: (prisma: PrismaService) => new PrismaAssistantShiftRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'IAssistantShiftAssignmentRepository',
      useFactory: (prisma: PrismaService) => new PrismaAssistantShiftAssignmentRepository(prisma),
      inject: [PrismaService],
    },
    {
      provide: 'PASSWORD_SERVICE',
      useClass: PasswordService,
    },
    {
      provide: 'JWT_TOKEN_SERVICE',
      useClass: JwtTokenService,
    },
    {
      provide: 'TOKEN_HASH_SERVICE',
      useClass: TokenHashService,
    },
    TokenService,
    {
      provide: 'HTTP_CLIENT_SERVICE',
      useClass: HttpClientService,
    },
    {
      provide: 'AUTH_SERVICE',
      useClass: AuthService,
    },
    {
      provide: 'IEmailService',
      useClass: ResendEmailService,
    },
    // {
    //   provide: 'IStorageService',
    //   useClass: SupabaseStorageService, // Disabled: not using Supabase anymore
    // },
    MediaProcessingService,
    DocumentThumbnailService,
    DocumentContentExtractionService,
    DocumentSeoAiService,
    TeacherProfileSeoAiService,
    AchievementBoardSeoAiService,
    NewsArticleSeoAiService,
    DocumentMediaAltTextAiService,
    ExcelService,
    MistralService,
    OpenAIService,
    CompetitionSubmitFeedbackAiService,
    ExamSplitService,
    MarkdownFixService,
    MarkdownRenderService,
    QuestionChapterClassificationService,
    FileConverterService,
    ZaloService,
    GoogleAdminStrategy,
    GoogleStudentStrategy,
    ImageExportService,
    QuestionChatAIService,
    VnpayService,
    PayosService,
    SepayService,
  ],
  exports: [
    AchievementBoardSeoAiServicePort,
    AuthServicePort,
    CompetitionSubmitFeedbackAiServicePort,
    DocumentContentExtractionServicePort,
    DocumentMediaAltTextAiServicePort,
    DocumentSeoAiServicePort,
    DocumentThumbnailServicePort,
    ExamSplitServicePort,
    ExcelServicePort,
    FileConverterServicePort,
    HttpClientServicePort,
    ImageExportServicePort,
    JwtTokenServicePort,
    MarkdownFixServicePort,
    MarkdownRenderServicePort,
    MediaProcessingServicePort,
    MistralServicePort,
    NewsArticleSeoAiServicePort,
    PasswordServicePort,
    PayosServicePort,
    SepayServicePort,
    QuestionChapterClassificationServicePort,
    QuestionChatAIServicePort,
    TeacherProfileSeoAiServicePort,
    TokenHashServicePort,
    TokenServicePort,
    VnpayServicePort,
    ZaloServicePort,
    'UNIT_OF_WORK',
    'IUserRepository',
    'IAdminRepository',
    'IStudentRepository',
    'IRoleRepository',
    'IPermissionRepository',
    'IClassStudentRepository',
    'ICourseEnrollmentRepository',
    'IAttendanceRepository',
    'INotificationRepository',
    'IAdminAuditLogRepository',
    'IBackgroundJobRepository',
    'IBackgroundJobRunRepository',
    'IBackgroundJobLockRepository',
    'ISepayTransactionSyncCursorRepository',
    'IStudentRepository',
    'IEmailVerificationTokenRepository',
    'IPasswordResetTokenRepository',
    'IZaloTokenRepository',
    'IMediaRepository',
    'IMediaFolderRepository',
    'IMediaUsageRepository',
    'ISeoMediaSlotRepository',
    'ISeoMediaItemRepository',
    'ICourseRepository',
    'ICourseClassRepository',
    'ILessonRepository',
    'ILearningItemRepository',
    'IStudentLearningItemRepository',
    'ILessonLearningItemRepository',
    'IClassSessionRepository',
    'ITuitionPaymentRepository',
    'IReceivingBankAccountRepository',
    'ITuitionGradeReceivingBankAccountRepository',
    'ITuitionCollectionConfigurationRepository',
    'IPaymentIntentRepository',
    'IPaymentAttemptRepository',
    'IBankTransferTransactionRepository',
    'ITempExamRepository',
    'ITempSectionRepository',
    'ICompetitionRepository',
    'ICompetitionSubmitRepository',
    'ICompetitionAnswerRepository',
    'ITempQuestionRepository',
    'ITempStatementRepository',
    'ITempQuestionChapterRepository',
    'IExamImportSessionRepository',
    'IExamRepository',
    'IExamAttemptRepository',
    'ISectionRepository',
    'IQuestionRepository',
    'IQuestionAnswerRepository',
    'IStatementRepository',
    'IQuestionExamRepository',
    'IQuestionChapterRepository',
    'IDocumentContentRepository',
    'IVideoContentRepository',
    'IYoutubeContentRepository',
    'IHomeworkContentRepository',
    'IHomeworkSubmitRepository',
    'IQuestionChatMessageRepository',
    'IQuestionChatRepository',
    'IDocumentRepository',
    'ITeacherProfileRepository',
    'ITagRepository',
    'IDocumentTagRepository',
    'IOnlineCourseInvoiceRepository',
    'IOnlineCourseInvoiceItemRepository',
    'IOnlineCoursePaymentAttemptRepository',
    'IStudentPointLogRepository',
    'IAchievementBoardRepository',
    'INewsArticleRepository',
    'IReportRepository',
    'IAssistantShiftSeriesRepository',
    'IAssistantShiftRepository',
    'IAssistantShiftAssignmentRepository',
    'PASSWORD_SERVICE',
    'JWT_TOKEN_SERVICE',
    'TOKEN_HASH_SERVICE',
    TokenService,
    'HTTP_CLIENT_SERVICE',
    'AUTH_SERVICE',
    'IEmailService',
    // 'IStorageService', // Disabled: not using Supabase anymore
    MediaProcessingService,
    DocumentThumbnailService,
    DocumentContentExtractionService,
    DocumentSeoAiService,
    TeacherProfileSeoAiService,
    AchievementBoardSeoAiService,
    NewsArticleSeoAiService,
    DocumentMediaAltTextAiService,
    ExcelService,
    MistralService,
    OpenAIService,
    CompetitionSubmitFeedbackAiService,
    ExamSplitService,
    MarkdownFixService,
    MarkdownRenderService,
    QuestionChapterClassificationService,
    FileConverterService,
    ZaloService,
    ImageExportService,
    QuestionChatAIService,
    VnpayService,
    PayosService,
    SepayService,
  ],
})
export class InfrastructureModule {}
