import { Body, Controller, Delete, Get, HttpCode, HttpStatus, Param, ParseIntPipe, Post, Put, Query, Res } from '@nestjs/common'
import type { Response } from 'express'
import { AssistantShiftAllBySeriesQueryDto, AssistantShiftDateRangeQueryDto, AssistantShiftRangeDto, CopyAssistantShiftsDto, CreateAssistantShiftDto, SetAssistantShiftSelfRegistrationWindowDto, UpdateAssistantShiftDto } from '../../application/dtos'
import { CancelAssistantShiftRegistrationUseCase, CheckInAssistantShiftUseCase, CopyAssistantShiftsBySeriesUseCase, CreateAssistantShiftUseCase, DeleteAssistantShiftUseCase, GetAllAssistantShiftsBySeriesUseCase, GetAssistantShiftAssistantStatisticsUseCase, GetAssistantShiftUseCase, GetAvailableAssistantShiftUseCase, GetAvailableAssistantShiftsBySeriesUseCase, GetMyAssistantShiftMonthlyStatisticsUseCase, GetMyAssistantShiftsUseCase, LockAssistantShiftsBySeriesUseCase, RegisterAssistantShiftUseCase, SetAssistantShiftSelfRegistrationWindowBySeriesUseCase, UnlockAssistantShiftsBySeriesUseCase, UpdateAssistantShiftUseCase } from '../../application/use-cases/assistant-shift'
import { PERMISSION_CODES } from '../../shared/constants/permissions/permission.codes'
import { CurrentUser } from '../../shared/decorators/current-user.decorator'
import { RequirePermission } from '../../shared/decorators/permissions.decorator'
import { ExceptionHandler } from '../../shared/utils/exception-handler.util'
import { renderAssistantShiftCheckInResultPage } from '../templates/assistant-shift-check-in-result.template'

@Controller('assistant-shifts')
export class AssistantShiftController {
  constructor(private readonly availableList: GetAvailableAssistantShiftsBySeriesUseCase, private readonly allList: GetAllAssistantShiftsBySeriesUseCase, private readonly mySchedule: GetMyAssistantShiftsUseCase, private readonly myMonthlyStatistics: GetMyAssistantShiftMonthlyStatisticsUseCase, private readonly assistantStatistics: GetAssistantShiftAssistantStatisticsUseCase, private readonly availableDetail: GetAvailableAssistantShiftUseCase, private readonly detail: GetAssistantShiftUseCase, private readonly createUseCase: CreateAssistantShiftUseCase, private readonly updateUseCase: UpdateAssistantShiftUseCase, private readonly deleteUseCase: DeleteAssistantShiftUseCase, private readonly registerUseCase: RegisterAssistantShiftUseCase, private readonly cancelRegistrationUseCase: CancelAssistantShiftRegistrationUseCase, private readonly checkInUseCase: CheckInAssistantShiftUseCase, private readonly copyUseCase: CopyAssistantShiftsBySeriesUseCase, private readonly lockUseCase: LockAssistantShiftsBySeriesUseCase, private readonly unlockUseCase: UnlockAssistantShiftsBySeriesUseCase, private readonly setSelfRegistrationWindowUseCase: SetAssistantShiftSelfRegistrationWindowBySeriesUseCase) {}
  @Get('series/:seriesId/available') @RequirePermission(PERMISSION_CODES.ASSISTANT_SHIFT.GET_AVAILABLE_BY_SERIES) listAvailable(@Param('seriesId', ParseIntPipe) id: number, @Query() query: AssistantShiftDateRangeQueryDto) { return ExceptionHandler.execute(() => this.availableList.execute(id, query)) }
  @Get('series/:seriesId') @RequirePermission(PERMISSION_CODES.ASSISTANT_SHIFT.GET_ALL_BY_SERIES) listAll(@Param('seriesId', ParseIntPipe) id: number, @Query() query: AssistantShiftAllBySeriesQueryDto) { return ExceptionHandler.execute(() => this.allList.execute(id, query)) }
  @Post('series/:seriesId/copy') @RequirePermission(PERMISSION_CODES.ASSISTANT_SHIFT.COPY) @HttpCode(HttpStatus.CREATED) copy(@Param('seriesId', ParseIntPipe) id: number, @Body() dto: CopyAssistantShiftsDto) { return ExceptionHandler.execute(() => this.copyUseCase.execute(id, dto)) }
  @Put('series/:seriesId/lock') @RequirePermission(PERMISSION_CODES.ASSISTANT_SHIFT.LOCK_BY_SERIES) @HttpCode(HttpStatus.OK) lock(@Param('seriesId', ParseIntPipe) id: number, @Body() dto: AssistantShiftRangeDto) { return ExceptionHandler.execute(() => this.lockUseCase.execute(id, dto)) }
  @Put('series/:seriesId/unlock') @RequirePermission(PERMISSION_CODES.ASSISTANT_SHIFT.UNLOCK_BY_SERIES) @HttpCode(HttpStatus.OK) unlock(@Param('seriesId', ParseIntPipe) id: number, @Body() dto: AssistantShiftRangeDto) { return ExceptionHandler.execute(() => this.unlockUseCase.execute(id, dto)) }
  @Put('series/:seriesId/self-registration-window') @RequirePermission(PERMISSION_CODES.ASSISTANT_SHIFT.SET_SELF_REGISTRATION_WINDOW_BY_SERIES) @HttpCode(HttpStatus.OK) setSelfRegistrationWindow(@Param('seriesId', ParseIntPipe) id: number, @Body() dto: SetAssistantShiftSelfRegistrationWindowDto) { return ExceptionHandler.execute(() => this.setSelfRegistrationWindowUseCase.execute(id, dto)) }
  @Get('statistics') @RequirePermission(PERMISSION_CODES.ASSISTANT_SHIFT.GET_ALL_BY_SERIES) @HttpCode(HttpStatus.OK) getAssistantStatistics(@Query() query: AssistantShiftDateRangeQueryDto) { return ExceptionHandler.execute(() => this.assistantStatistics.execute(query)) }
  @Get('my/monthly-statistics') @RequirePermission(PERMISSION_CODES.ASSISTANT_SHIFT.GET_MY_MONTHLY_STATISTICS) @HttpCode(HttpStatus.OK) getMyMonthlyStatistics(@CurrentUser('adminId') adminId: number) { return ExceptionHandler.execute(() => this.myMonthlyStatistics.execute(adminId)) }
  @Get('my') @RequirePermission(PERMISSION_CODES.ASSISTANT_SHIFT.GET_MY_SCHEDULE) @HttpCode(HttpStatus.OK) getMySchedule(@CurrentUser('adminId') adminId: number, @Query() query: AssistantShiftDateRangeQueryDto) { return ExceptionHandler.execute(() => this.mySchedule.execute(adminId, query)) }
  @Post() @RequirePermission(PERMISSION_CODES.ASSISTANT_SHIFT.CREATE) @HttpCode(HttpStatus.CREATED) create(@Body() dto: CreateAssistantShiftDto) { return ExceptionHandler.execute(() => this.createUseCase.execute(dto)) }
  @Get(':id/available') @RequirePermission(PERMISSION_CODES.ASSISTANT_SHIFT.GET_AVAILABLE_DETAIL) getAvailable(@Param('id', ParseIntPipe) id: number) { return ExceptionHandler.execute(() => this.availableDetail.execute(id)) }
  @Post(':id/register') @RequirePermission(PERMISSION_CODES.ASSISTANT_SHIFT.REGISTER) @HttpCode(HttpStatus.CREATED) register(@Param('id', ParseIntPipe) id: number, @CurrentUser('adminId') adminId: number) { return ExceptionHandler.execute(() => this.registerUseCase.execute(id, adminId)) }
  @Delete(':id/register') @RequirePermission(PERMISSION_CODES.ASSISTANT_SHIFT.CANCEL_REGISTRATION) @HttpCode(HttpStatus.OK) cancelRegistration(@Param('id', ParseIntPipe) id: number, @CurrentUser('adminId') adminId: number) { return ExceptionHandler.execute(() => this.cancelRegistrationUseCase.execute(id, adminId)) }
  @Get(':id/check-in') @HttpCode(HttpStatus.OK) async checkIn(@Param('id', ParseIntPipe) id: number, @Query('token') token: string | undefined, @Res() response: Response): Promise<void> { const result = await this.checkInUseCase.execute(id, token); response.type('html').send(renderAssistantShiftCheckInResultPage(result)) }
  @Get(':id') @RequirePermission(PERMISSION_CODES.ASSISTANT_SHIFT.GET_DETAIL) get(@Param('id', ParseIntPipe) id: number) { return ExceptionHandler.execute(() => this.detail.execute(id)) }
  @Put(':id') @RequirePermission(PERMISSION_CODES.ASSISTANT_SHIFT.UPDATE) update(@Param('id', ParseIntPipe) id: number, @Body() dto: UpdateAssistantShiftDto) { return ExceptionHandler.execute(() => this.updateUseCase.execute(id, dto)) }
  @Delete(':id') @RequirePermission(PERMISSION_CODES.ASSISTANT_SHIFT.DELETE) delete(@Param('id', ParseIntPipe) id: number) { return ExceptionHandler.execute(() => this.deleteUseCase.execute(id)) }
}
