export const PERMISSION_CODES = {
  EXAM: {
    GET_MY_EXAMS: 'exam:get-my-exams',
    GET_ALL: 'exam:get-all',
    GET_BY_ID: 'exam:get-by-id',
    SEARCH: 'exam:search',
    CREATE: 'exam:create',
    UPDATE: 'exam:update',
    DELETE: 'exam:delete',
  },
  COMPETITION: {
    GET_MY_COMPETITIONS: 'competition:get-my-competitions',
    GET_ALL: 'competition:get-all',
    GET_BY_ID: 'competition:get-by-id',
    SEARCH: 'competition:search',
    CREATE: 'competition:create',
    UPDATE: 'competition:update',
    DELETE: 'competition:delete',
  },
  COMPETITION_SUBMIT: {
    GET_ALL: 'competition-submit:get-all',
    GET_BY_ID: 'competition-submit:get-by-id',
    UPDATE: 'competition-submit:update',
    DELETE: 'competition-submit:delete',
    GET_MY_HISTORY: 'competition-submit:get-my-history',
    REGRADE: 'competition-submit:regrade',
    EXPORT_EXCEL: 'competition-submit:export-excel',
  },
  QUESTION: {
    GET_MY_QUESTIONS: 'question:get-my-questions',
    SEARCH: 'question:search',
    GET_ALL: 'question:get-all',
    GET_BY_ID: 'question:get-by-id',
    CREATE: 'question:create',
    REORDER: 'question:reorder',
    UPDATE: 'question:update',
    ADD_TO_EXAM: 'question:add-to-exam',
    ADD_TO_SECTION: 'question:add-to-section',
    REMOVE_FROM_EXAM: 'question:remove-from-exam',
    DELETE: 'question:delete',
  },
  SECTION: {
    GET_BY_EXAM: 'section:get-by-exam',
    GET_BY_ID: 'section:get-by-id',
    CREATE: 'section:create',
    UPDATE: 'section:update',
    DELETE: 'section:delete',
  },
  STATEMENT: {
    CREATE: 'statement:create',
    UPDATE: 'statement:update',
    DELETE: 'statement:delete',
  },
  COURSE: {
    GET_ALL: 'course:get-all',
    SEARCH: 'course:search',
    GET_MY_COURSES: 'course:get-my-courses',
    GET_BY_ID: 'course:get-by-id',
    CREATE: 'course:create',
    UPDATE: 'course:update',
    UPDATE_PRICING: 'course:update-pricing',
    DELETE: 'course:delete',
    GET_STUDENTS_ATTENDANCE: 'course:get-students-attendance',
  },
  STUDENT: {
    GET_ALL: 'student:get-all',
    SEARCH: 'student:search',
    GET_BY_ID: 'student:get-by-id',
    CREATE: 'student:create',
    UPDATE: 'student:update',
    EXPORT_EXCEL: 'student:export-excel',
  },
  SUBJECT: {
    GET_ALL: 'subject:get-all',
    GET_BY_ID: 'subject:get-by-id',
    CREATE: 'subject:create',
    UPDATE: 'subject:update',
    DELETE: 'subject:delete',
  },
  LESSON: {
    GET_ALL: 'lesson:get-all',
    GET_BY_ID: 'lesson:get-by-id',
    CREATE: 'lesson:create',
    UPDATE: 'lesson:update',
    DELETE: 'lesson:delete',
  },
  CHAPTER: {
    GET_ALL: 'chapter:get-all',
    GET_BY_ID: 'chapter:get-by-id',
    CREATE: 'chapter:create',
    UPDATE: 'chapter:update',
    DELETE: 'chapter:delete',
  },
  ADMIN: {
    GET_ALL: 'admin:get-all',
    SEARCH: 'admin:search',
    GET_BY_ID: 'admin:get-by-id',
    CREATE: 'admin:create',
  },
  ROLE: {
    GET_ALL: 'role:get-all',
    GET_BY_ID: 'role:get-by-id',
    CREATE: 'role:create',
    UPDATE: 'role:update',
    DELETE: 'role:delete',
    ASSIGN: 'role:assign',
    REMOVE_FROM_USER: 'role:remove-from-user',
    GET_USER_ROLES: 'role:get-user-roles',
    TOGGLE_ROLE_PERMISSION: 'role:toggle-role-permission',
  },
  PERMISSION: {
    GET_ALL: 'permission:get-all',
    GET_BY_ID: 'permission:get-by-id',
    GET_GROUPS: 'permission:get-groups',
    CREATE: 'permission:create',
    UPDATE: 'permission:update',
    DELETE: 'permission:delete',
    SYNC_FROM_CODES: 'permission:sync-from-codes',
  },
  USER: {
    TOGGLE_ACTIVATION: 'user:toggle-activation',
  },
  MEDIA: {
    UPLOAD: 'media:upload',
    GET_ALL: 'media:get-all',
    GET_MY_MEDIA: 'media:get-my-media',
    GET_BUCKETS: 'media:get-buckets',
    GET_BY_ID: 'media:get-by-id',
    UPDATE: 'media:update',
    DOWNLOAD: 'media:download',
    VIEW_MY: 'media:view-my',
    ADMIN_VIEW: 'media:admin-view',
    ADMIN_DOWNLOAD: 'media:admin-download',
    DOWNLOAD_MY: 'media:download-my',
    GET_STATISTICS_BUCKETS: 'media:get-statistics-buckets',
    DELETE: 'media:delete',
    PERMANENT_DELETE: 'media:permanent-delete',
    DELETE_MY: 'media:delete-my',
  },
  ATTENDANCE: {
    GET_ALL: 'attendance:get-all',
    GET_ALL_BY_SESSION: 'attendance:get-all-by-session',
    GET_MY_ATTENDANCES: 'attendance:get-my-attendances',
    GET_BY_ID: 'attendance:get-by-id',
    CREATE: 'attendance:create',
    UPDATE: 'attendance:update',
    DELETE: 'attendance:delete',
  },
  CLASS_SESSION: {
    GET_ALL: 'class-session:get-all',
    SEARCH: 'class-session:search',
    GET_BY_ID: 'class-session:get-by-id',
    CREATE: 'class-session:create',
    UPDATE: 'class-session:update',
    DELETE: 'class-session:delete',
  },
  COURSE_CLASS: {
    GET_ALL: 'course-class:get-all',
    SEARCH: 'course-class:search',
    GET_MY_CLASSES: 'course-class:get-my-classes',
    GET_BY_ID: 'course-class:get-by-id',
    CREATE: 'course-class:create',
    UPDATE: 'course-class:update',
    DELETE: 'course-class:delete',
  },
  COURSE_ENROLLMENT: {
    GET_ALL: 'course-enrollment:get-all',
    GET_MY_ENROLLMENTS: 'course-enrollment:get-my-enrollments',
    GET_BY_ID: 'course-enrollment:get-by-id',
    CREATE: 'course-enrollment:create',
    UPDATE: 'course-enrollment:update',
    DELETE: 'course-enrollment:delete',
    EXPORT_EXCEL: 'course-enrollment:export-excel',
  },
  NOTIFICATION: {
    GET_MY: 'notification:get-my',
    GET_BY_USER_ID: 'notification:get-by-user-id',
    MARK_READ: 'notification:mark-read',
    DELETE: 'notification:delete',
    SEND: 'notification:send',
  },
  MEDIA_FOLDER: {
    CREATE: 'media-folder:create',
    VIEW: 'media-folder:view',
    UPDATE: 'media-folder:update',
    DELETE: 'media-folder:delete',
  },
  MEDIA_USAGE: {
    ATTACH: 'media-usage:attach',
    GET_ALL: 'media-usage:get-all',
    GET_BY_MEDIA: 'media-usage:get-by-media',
    GET_BY_ENTITY: 'media-usage:get-by-entity',
    DETACH: 'media-usage:detach',
  },
  SEO_MEDIA: {
    UPLOAD_MEDIA: 'seo-media:upload-media',
    UPLOAD_IMAGE: 'seo-media:upload-image',
    BUCKET_MEDIA_VIEW: 'seo-media:bucket-media:view',
    SLOT_CREATE: 'seo-media:slot:create',
    SLOT_VIEW: 'seo-media:slot:view',
    SLOT_UPDATE: 'seo-media:slot:update',
    SLOT_DELETE: 'seo-media:slot:delete',
    ITEM_CREATE: 'seo-media:item:create',
    ITEM_VIEW: 'seo-media:item:view',
    ITEM_UPDATE: 'seo-media:item:update',
    ITEM_DELETE: 'seo-media:item:delete',
    ITEM_REORDER: 'seo-media:item:reorder',
  },
  LEARNING_ITEM: {
    GET_ALL: 'learning-item:get-all',
    GET_MY_LEARNING_ITEMS: 'learning-item:get-my-learning-items',
    GET_BY_ID: 'learning-item:get-by-id',
    CREATE: 'learning-item:create',
    UPDATE: 'learning-item:update',
    DELETE: 'learning-item:delete',
  },
  TUITION_PAYMENT: {
    STATS: 'tuition-payment:stats',
    GET_ALL: 'tuition-payment:get-all',
    GET_BY_COURSE: 'tuition-payment:get-by-course',
    GET_BY_STUDENT: 'tuition-payment:get-by-student',
    GET_MY: 'tuition-payment:get-my',
    GET_BY_ID: 'tuition-payment:get-by-id',
    CREATE: 'tuition-payment:create',
    CREATE_BULK: 'tuition-payment:create-bulk',
    UPDATE: 'tuition-payment:update',
    DELETE: 'tuition-payment:delete',
    EXPORT_EXCEL: 'tuition-payment:export-excel',
    IMPORT_EXCEL: 'tuition-payment:import-excel',
  },
  ONLINE_COURSE_INVOICE: {
    GET_ALL: 'online-course-invoice:get-all',
    GET_BY_ID: 'online-course-invoice:get-by-id',
    CONFIRM_MANUAL_PAYMENT: 'online-course-invoice:confirm-manual-payment',
  },
  MY_TUITION_PAYMENT_STATS: 'my-tuition-payment:stats',
  TEMP_EXAM: {
    GET_BY_SESSION: 'temp-exam:get-by-session',
    CREATE: 'temp-exam:create',
    UPDATE: 'temp-exam:update',
  },
  TEMP_SECTION: {
    GET_BY_EXAM: 'temp-section:get-by-exam',
    GET_BY_ID: 'temp-section:get-by-id',
    CREATE: 'temp-section:create',
    UPDATE: 'temp-section:update',
    DELETE: 'temp-section:delete',
  },
  TEMP_QUESTION: {
    GET_BY_SESSION: 'temp-question:get-by-session',
    GET_BY_ID: 'temp-question:get-by-id',
    CREATE: 'temp-question:create',
    UPDATE: 'temp-question:update',
    DELETE: 'temp-question:delete',
  },
  TEMP_STATEMENT: {
    CREATE: 'temp-statement:create',
    UPDATE: 'temp-statement:update',
    DELETE: 'temp-statement:delete',
  },
  VIDEO_CONTENT: {
    GET_ALL: 'video-content:get-all',
    GET_BY_ID: 'video-content:get-by-id',
    CREATE: 'video-content:create',
    UPDATE: 'video-content:update',
    DELETE: 'video-content:delete',
  },
  YOUTUBE_CONTENT: {
    GET_ALL: 'youtube-content:get-all',
    GET_BY_ID: 'youtube-content:get-by-id',
    CREATE: 'youtube-content:create',
    UPDATE: 'youtube-content:update',
    DELETE: 'youtube-content:delete',
  },
  AUDIT_LOG: {
    GET_ALL: 'audit-log:get-all',
    GET_ALL_BY_ADMIN: 'audit-log:get-all-by-admin',
    GET_BY_ID: 'audit-log:get-by-id',
    ROLLBACK: 'audit-log:rollback',
  },
  CLASS_STUDENT: {
    GET_ALL: 'class-student:get-all',
    GET_MY_CLASSES: 'class-student:get-my-classes',
    CREATE: 'class-student:create',
    DELETE: 'class-student:delete',
  },
  DOCUMENT_CONTENT: {
    GET_ALL: 'document-content:get-all',
    GET_BY_ID: 'document-content:get-by-id',
    CREATE: 'document-content:create',
    UPDATE: 'document-content:update',
    DELETE: 'document-content:delete',
  },
  EXAM_IMPORT_SESSION: {
    GET_ALL: 'exam-import-session:get-all',
    CREATE: 'exam-import-session:create',
    GET_BY_ID: 'exam-import-session:get-by-id',
  },
  HOMEWORK_CONTENT: {
    GET_ALL: 'homework-content:get-all',
    GET_BY_ID: 'homework-content:get-by-id',
    CREATE: 'homework-content:create',
    UPDATE: 'homework-content:update',
    DELETE: 'homework-content:delete',
  },
  HOMEWORK_SUBMIT: {
    GET_ALL: 'homework-submit:get-all',
    GET_BY_ID: 'homework-submit:get-by-id',
    CREATE: 'homework-submit:create',
    UPDATE: 'homework-submit:update',
    GRADE: 'homework-submit:grade',
    DELETE: 'homework-submit:delete',
  },
  LESSON_LEARNING_ITEM: {
    GET_ALL: 'lesson-learning-item:get-all',
    GET_BY_ID: 'lesson-learning-item:get-by-id',
    CREATE: 'lesson-learning-item:create',
    UPDATE: 'lesson-learning-item:update',
    DELETE: 'lesson-learning-item:delete',
  },

  // ===================================
  // ADMIN PAGE PERMISSIONS
  // ===================================
  ADMIN_PAGE: {
    DASHBOARD: 'admin:page:dashboard',
    ROLES: 'admin:page:roles',
    ROLE_CREATE: 'admin:page:role-create',
    ROLE_EDIT: 'admin:page:role-edit',
    PERMISSIONS: 'admin:page:permissions',
    AUDIT_LOGS: 'admin:page:audit-logs',
    MEDIA: 'admin:page:media',
    MEDIA_FOLDERS: 'admin:page:media-folders',
    SEO_MEDIA: 'admin:page:seo-media',
    ADMINS: 'admin:page:admins',
    ADMIN_DETAIL: 'admin:page:admin-detail',
    STUDENTS: 'admin:page:students',
    STUDENT_DETAIL: 'admin:page:student-detail',
    CHAPTERS: 'admin:page:chapters',
    SUBJECTS: 'admin:page:subjects',
    COURSES: 'admin:page:courses',
    COURSE_DETAIL: 'admin:page:course-detail',
    MY_COURSES: 'admin:page:my-courses',
    CLASSES: 'admin:page:classes',
    CLASS_DETAIL: 'admin:page:class-detail',
    MY_CLASSES: 'admin:page:my-classes',
    BROADCAST_NOTIFICATIONS: 'admin:page:broadcast-notifications',
    TUITION_PAYMENTS: 'admin:page:tuition-payments',
    EXAM_IMPORT_SESSIONS: 'admin:page:exam-import-sessions',
    QUESTIONS: 'admin:page:questions',
    MY_QUESTIONS: 'admin:page:my-questions',
    EXAMS: 'admin:page:exams',
    MY_EXAMS: 'admin:page:my-exams',
    COMPETITIONS: 'admin:page:competitions',
    MY_COMPETITIONS: 'admin:page:my-competitions',
  },
}

export interface PermissionCodeDefinition {
  code: string
  name: string
  description: string
  group: string
  isSystem: boolean
}

type PermissionCodeTree = string | { readonly [key: string]: PermissionCodeTree }
export type PermissionCodeDefinitionTree =
  | PermissionCodeDefinition
  | { readonly [key: string]: PermissionCodeDefinitionTree }

const PERMISSION_GROUPS_BY_KEY: Record<string, string> = {
  EXAM: 'EXAM_MANAGEMENT',
  COMPETITION: 'COMPETITION_MANAGEMENT',
  COMPETITION_SUBMIT: 'COMPETITION_SUBMIT_MANAGEMENT',
  QUESTION: 'QUESTION_MANAGEMENT',
  SECTION: 'SECTION_MANAGEMENT',
  STATEMENT: 'STATEMENT_MANAGEMENT',
  COURSE: 'COURSE_MANAGEMENT',
  STUDENT: 'STUDENT_MANAGEMENT',
  SUBJECT: 'SUBJECT_MANAGEMENT',
  LESSON: 'LESSON_MANAGEMENT',
  CHAPTER: 'CHAPTER_MANAGEMENT',
  ADMIN: 'ADMIN_MANAGEMENT',
  ROLE: 'ROLE_MANAGEMENT',
  PERMISSION: 'PERMISSION_MANAGEMENT',
  USER: 'USER_MANAGEMENT',
  MEDIA: 'MEDIA_MANAGEMENT',
  ATTENDANCE: 'ATTENDANCE_MANAGEMENT',
  CLASS_SESSION: 'CLASS_SESSION_MANAGEMENT',
  COURSE_CLASS: 'COURSE_CLASS_MANAGEMENT',
  COURSE_ENROLLMENT: 'COURSE_ENROLLMENT_MANAGEMENT',
  NOTIFICATION: 'NOTIFICATION_MANAGEMENT',
  MEDIA_FOLDER: 'MEDIA_FOLDER_MANAGEMENT',
  MEDIA_USAGE: 'MEDIA_USAGE_MANAGEMENT',
  SEO_MEDIA: 'SEO_MEDIA_MANAGEMENT',
  LEARNING_ITEM: 'LEARNING_ITEM_MANAGEMENT',
  TUITION_PAYMENT: 'TUITION_PAYMENT_MANAGEMENT',
  ONLINE_COURSE_INVOICE: 'ONLINE_COURSE_INVOICE_MANAGEMENT',
  MY_TUITION_PAYMENT_STATS: 'TUITION_PAYMENT_MANAGEMENT',
  TEMP_EXAM: 'TEMP_EXAM_MANAGEMENT',
  TEMP_SECTION: 'TEMP_SECTION_MANAGEMENT',
  TEMP_QUESTION: 'TEMP_QUESTION_MANAGEMENT',
  TEMP_STATEMENT: 'TEMP_STATEMENT_MANAGEMENT',
  VIDEO_CONTENT: 'VIDEO_CONTENT_MANAGEMENT',
  YOUTUBE_CONTENT: 'YOUTUBE_CONTENT_MANAGEMENT',
  AUDIT_LOG: 'AUDIT_LOG_MANAGEMENT',
  CLASS_STUDENT: 'CLASS_STUDENT_MANAGEMENT',
  DOCUMENT_CONTENT: 'DOCUMENT_CONTENT_MANAGEMENT',
  EXAM_IMPORT_SESSION: 'EXAM_IMPORT_SESSION_MANAGEMENT',
  HOMEWORK_CONTENT: 'HOMEWORK_CONTENT_MANAGEMENT',
  HOMEWORK_SUBMIT: 'HOMEWORK_SUBMIT_MANAGEMENT',
  LESSON_LEARNING_ITEM: 'LESSON_LEARNING_ITEM_MANAGEMENT',
  ADMIN_PAGE: 'ADMIN_PAGE_ACCESS',
}

const PERMISSION_RESOURCE_LABELS_BY_KEY: Record<string, string> = {
  EXAM: 'exam',
  COMPETITION: 'competition',
  COMPETITION_SUBMIT: 'competition submission',
  QUESTION: 'question',
  SECTION: 'section',
  STATEMENT: 'statement',
  COURSE: 'course',
  STUDENT: 'student',
  SUBJECT: 'subject',
  LESSON: 'lesson',
  CHAPTER: 'chapter',
  ADMIN: 'admin',
  ROLE: 'role',
  PERMISSION: 'permission',
  USER: 'user',
  MEDIA: 'media',
  ATTENDANCE: 'attendance',
  CLASS_SESSION: 'class session',
  COURSE_CLASS: 'course class',
  COURSE_ENROLLMENT: 'course enrollment',
  NOTIFICATION: 'notification',
  MEDIA_FOLDER: 'media folder',
  MEDIA_USAGE: 'media usage',
  SEO_MEDIA: 'SEO media',
  LEARNING_ITEM: 'learning item',
  TUITION_PAYMENT: 'tuition payment',
  ONLINE_COURSE_INVOICE: 'online course invoice',
  MY_TUITION_PAYMENT_STATS: 'my tuition payment stats',
  TEMP_EXAM: 'temporary exam',
  TEMP_SECTION: 'temporary section',
  TEMP_QUESTION: 'temporary question',
  TEMP_STATEMENT: 'temporary statement',
  VIDEO_CONTENT: 'video content',
  YOUTUBE_CONTENT: 'YouTube content',
  AUDIT_LOG: 'audit log',
  CLASS_STUDENT: 'class student',
  DOCUMENT_CONTENT: 'document content',
  EXAM_IMPORT_SESSION: 'exam import session',
  HOMEWORK_CONTENT: 'homework content',
  HOMEWORK_SUBMIT: 'homework submission',
  LESSON_LEARNING_ITEM: 'lesson learning item',
  ADMIN_PAGE: 'admin page',
}

const PERMISSION_ACTION_LABELS_BY_KEY: Record<string, string> = {
  GET_ALL: 'View all',
  GET_BY_ID: 'View detail',
  GET_BY_EXAM: 'View by exam',
  GET_BY_SESSION: 'View by session',
  GET_BY_COURSE: 'View by course',
  GET_BY_STUDENT: 'View by student',
  GET_BY_USER_ID: 'View by user',
  GET_BY_MEDIA: 'View by media',
  GET_BY_ENTITY: 'View by entity',
  GET_MY: 'View my',
  GET_MY_EXAMS: 'View my exams',
  GET_MY_COMPETITIONS: 'View my competitions',
  GET_MY_HISTORY: 'View my history',
  GET_MY_QUESTIONS: 'View my questions',
  GET_MY_COURSES: 'View my courses',
  GET_MY_CLASSES: 'View my classes',
  GET_MY_MEDIA: 'View my media',
  GET_MY_ATTENDANCES: 'View my attendance',
  GET_MY_ENROLLMENTS: 'View my enrollments',
  GET_MY_LEARNING_ITEMS: 'View my learning items',
  SEARCH: 'Search',
  CREATE: 'Create',
  CREATE_BULK: 'Bulk create',
  UPDATE: 'Update',
  UPDATE_PRICING: 'Update pricing',
  DELETE: 'Delete',
  DELETE_MY: 'Delete my',
  PERMANENT_DELETE: 'Permanent delete',
  EXPORT_EXCEL: 'Export Excel',
  IMPORT_EXCEL: 'Import Excel',
  ASSIGN: 'Assign',
  REMOVE_FROM_USER: 'Remove from user',
  GET_USER_ROLES: 'View user roles',
  TOGGLE_ROLE_PERMISSION: 'Toggle role permission',
  GET_GROUPS: 'View groups',
  TOGGLE_ACTIVATION: 'Toggle activation',
  UPLOAD: 'Upload',
  DOWNLOAD: 'Download',
  DOWNLOAD_MY: 'Download my',
  VIEW: 'View',
  VIEW_MY: 'View my',
  ADMIN_VIEW: 'Admin view',
  ADMIN_DOWNLOAD: 'Admin download',
  GET_BUCKETS: 'View buckets',
  GET_STATISTICS_BUCKETS: 'View storage bucket statistics',
  GET_ALL_BY_SESSION: 'View all by session',
  GET_STUDENTS_ATTENDANCE: 'View students attendance',
  MARK_READ: 'Mark read',
  SEND: 'Send',
  ATTACH: 'Attach',
  DETACH: 'Detach',
  UPLOAD_IMAGE: 'Upload image',
  UPLOAD_MEDIA: 'Upload media',
  BUCKET_MEDIA_VIEW: 'View bucket media',
  SLOT_CREATE: 'Create slot',
  SLOT_VIEW: 'View slot',
  SLOT_UPDATE: 'Update slot',
  SLOT_DELETE: 'Delete slot',
  ITEM_CREATE: 'Create item',
  ITEM_VIEW: 'View item',
  ITEM_UPDATE: 'Update item',
  ITEM_DELETE: 'Delete item',
  ITEM_REORDER: 'Reorder item',
  STATS: 'View stats',
  REGRADE: 'Regrade',
  REORDER: 'Reorder',
  ADD_TO_EXAM: 'Add to exam',
  ADD_TO_SECTION: 'Add to section',
  REMOVE_FROM_EXAM: 'Remove from exam',
  GRADE: 'Grade',
  ROLLBACK: 'Rollback',
  SYNC_FROM_CODES: 'Sync from permission codes',
  CONFIRM_MANUAL_PAYMENT: 'Confirm manual payment',
}

const ADMIN_PAGE_LABELS_BY_KEY: Record<string, string> = {
  DASHBOARD: 'Dashboard',
  ROLES: 'Roles',
  ROLE_CREATE: 'Role create',
  ROLE_EDIT: 'Role edit',
  PERMISSIONS: 'Permissions',
  AUDIT_LOGS: 'Audit logs',
  MEDIA: 'Media',
  MEDIA_FOLDERS: 'Media folders',
  SEO_MEDIA: 'SEO media',
  ADMINS: 'Admins',
  ADMIN_DETAIL: 'Admin detail',
  STUDENTS: 'Students',
  STUDENT_DETAIL: 'Student detail',
  CHAPTERS: 'Chapters',
  SUBJECTS: 'Subjects',
  COURSES: 'Courses',
  COURSE_DETAIL: 'Course detail',
  MY_COURSES: 'My courses',
  CLASSES: 'Classes',
  CLASS_DETAIL: 'Class detail',
  MY_CLASSES: 'My classes',
  BROADCAST_NOTIFICATIONS: 'Broadcast notifications',
  TUITION_PAYMENTS: 'Tuition payments',
  EXAM_IMPORT_SESSIONS: 'Exam import sessions',
  QUESTIONS: 'Questions',
  MY_QUESTIONS: 'My questions',
  EXAMS: 'Exams',
  MY_EXAMS: 'My exams',
  COMPETITIONS: 'Competitions',
  MY_COMPETITIONS: 'My competitions',
}

const SELF_CONTAINED_ACTION_KEYS = new Set([
  'GET_MY_EXAMS',
  'GET_MY_COMPETITIONS',
  'GET_MY_HISTORY',
  'GET_MY_QUESTIONS',
  'GET_MY_COURSES',
  'GET_MY_CLASSES',
  'GET_MY_MEDIA',
  'GET_MY_ATTENDANCES',
  'GET_MY_ENROLLMENTS',
  'GET_MY_LEARNING_ITEMS',
  'GET_USER_ROLES',
  'TOGGLE_ROLE_PERMISSION',
  'GET_STATISTICS_BUCKETS',
  'GET_STUDENTS_ATTENDANCE',
  'SYNC_FROM_CODES',
])

export const PERMISSION_CODE_DEFINITIONS = buildPermissionCodeDefinitions(PERMISSION_CODES as PermissionCodeTree)

function buildPermissionCodeDefinitions(node: PermissionCodeTree, path: string[] = []): PermissionCodeDefinitionTree {
  if (typeof node === 'string') {
    const name = buildPermissionName(path)

    return {
      code: node,
      name,
      description: buildPermissionDescription(name, node),
      group: PERMISSION_GROUPS_BY_KEY[path[0]] || 'SYSTEM',
      isSystem: true,
    }
  }

  return Object.fromEntries(
    Object.entries(node).map(([key, value]) => [key, buildPermissionCodeDefinitions(value, [...path, key])]),
  )
}

function buildPermissionName(path: string[]): string {
  const resourceKey = path[0]
  const actionKey = path[path.length - 1]

  if (resourceKey === 'ADMIN_PAGE') {
    return `Access ${ADMIN_PAGE_LABELS_BY_KEY[actionKey] || toTitleCase(actionKey)} admin page`.slice(0, 100)
  }

  const actionLabel = PERMISSION_ACTION_LABELS_BY_KEY[actionKey] || toTitleCase(actionKey)
  const resourceLabel = PERMISSION_RESOURCE_LABELS_BY_KEY[resourceKey] || toTitleCase(resourceKey)

  if (SELF_CONTAINED_ACTION_KEYS.has(actionKey)) {
    return actionLabel.slice(0, 100)
  }

  return `${actionLabel} ${resourceLabel}`.slice(0, 100)
}

function buildPermissionDescription(name: string, code: string): string {
  return `Allows ${name.toLowerCase()} (${code}).`.slice(0, 255)
}

function toTitleCase(value: string): string {
  return value
    .toLowerCase()
    .split('_')
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}
