-- Tạo sẵn mapping cho toàn bộ khối 1..12. Bản ghi đã tồn tại được giữ nguyên account đã gán.
INSERT INTO `tuition_grade_receiving_bank_accounts` (
  `grade`,
  `receiving_bank_account_id`,
  `created_at`,
  `updated_at`
)
VALUES
  (1, NULL, CURRENT_TIMESTAMP(0), CURRENT_TIMESTAMP(0)),
  (2, NULL, CURRENT_TIMESTAMP(0), CURRENT_TIMESTAMP(0)),
  (3, NULL, CURRENT_TIMESTAMP(0), CURRENT_TIMESTAMP(0)),
  (4, NULL, CURRENT_TIMESTAMP(0), CURRENT_TIMESTAMP(0)),
  (5, NULL, CURRENT_TIMESTAMP(0), CURRENT_TIMESTAMP(0)),
  (6, NULL, CURRENT_TIMESTAMP(0), CURRENT_TIMESTAMP(0)),
  (7, NULL, CURRENT_TIMESTAMP(0), CURRENT_TIMESTAMP(0)),
  (8, NULL, CURRENT_TIMESTAMP(0), CURRENT_TIMESTAMP(0)),
  (9, NULL, CURRENT_TIMESTAMP(0), CURRENT_TIMESTAMP(0)),
  (10, NULL, CURRENT_TIMESTAMP(0), CURRENT_TIMESTAMP(0)),
  (11, NULL, CURRENT_TIMESTAMP(0), CURRENT_TIMESTAMP(0)),
  (12, NULL, CURRENT_TIMESTAMP(0), CURRENT_TIMESTAMP(0))
ON DUPLICATE KEY UPDATE `grade` = VALUES(`grade`);
