// src/shared/constants/action-key.constants.ts

export const ACTION_KEYS = {
  USER: {
    CREATE: 'CREATE_USER',
    UPDATE: 'UPDATE_USER',
    DELETE: 'DELETE_USER',
    TOGGLE_ACTIVATION: 'TOGGLE_USER_ACTIVATION',
  },
  ADMIN: {
    CREATE: 'CREATE_ADMIN',
    UPDATE: 'UPDATE_ADMIN',
    DELETE: 'DELETE_ADMIN',
  },
  STUDENT: {
    CREATE: 'CREATE_STUDENT',
    UPDATE: 'UPDATE_STUDENT',
    DELETE: 'DELETE_STUDENT',
  },
  ROLE: {
    CREATE: 'CREATE_ROLE',
    UPDATE: 'UPDATE_ROLE',
    DELETE: 'DELETE_ROLE',
    ASSIGN: 'ASSIGN_ROLE',
    REMOVE: 'REMOVE_ROLE',
    TOGGLE_PERMISSION: 'TOGGLE_ROLE_PERMISSION',
  },
  PERMISSION: {
    CREATE: 'CREATE_PERMISSION',
    UPDATE: 'UPDATE_PERMISSION',
    DELETE: 'DELETE_PERMISSION',
  },
  SUBJECT: {
    CREATE: 'CREATE_SUBJECT',
    UPDATE: 'UPDATE_SUBJECT',
    DELETE: 'DELETE_SUBJECT',
  },
  CHAPTER: {
    CREATE: 'CREATE_CHAPTER',
    UPDATE: 'UPDATE_CHAPTER',
    DELETE: 'DELETE_CHAPTER',
  },
  DOCUMENT: {
    CREATE: 'CREATE_DOCUMENT',
    UPDATE: 'UPDATE_DOCUMENT',
    DELETE: 'DELETE_DOCUMENT',
  },
  IMAGE: {
    CREATE: 'CREATE_IMAGE',
    UPDATE: 'UPDATE_IMAGE',
    DELETE: 'DELETE_IMAGE',
  },
  ATTENDANCE: {
    CREATE: 'CREATE_ATTENDANCE',
    UPDATE: 'UPDATE_ATTENDANCE',
    DELETE: 'DELETE_ATTENDANCE',
    CREATE_BULK: 'CREATE_BULK_ATTENDANCE',
  },
  CLASS_SESSION: {
    CREATE: 'CREATE_CLASS_SESSION',
    UPDATE: 'UPDATE_CLASS_SESSION',
    DELETE: 'DELETE_CLASS_SESSION',
  },
  CLASS_STUDENT: {
    DELETE: 'DELETE_CLASS_STUDENT',
  },
  COURSE: {
    CREATE: 'CREATE_COURSE',
    UPDATE: 'UPDATE_COURSE',
    DELETE: 'DELETE_COURSE',
  },
  COURSE_CLASS: {
    CREATE: 'CREATE_COURSE_CLASS',
    UPDATE: 'UPDATE_COURSE_CLASS',
    DELETE: 'DELETE_COURSE_CLASS',
  },
  COURSE_ENROLLMENT: {
    CREATE: 'CREATE_COURSE_ENROLLMENT',
    UPDATE: 'UPDATE_COURSE_ENROLLMENT',
    DELETE: 'DELETE_COURSE_ENROLLMENT',
  },
  LEARNING_ITEM: {
    CREATE: 'CREATE_LEARNING_ITEM',
    UPDATE: 'UPDATE_LEARNING_ITEM',
    DELETE: 'DELETE_LEARNING_ITEM',
  },
  DOCUMENT_CONTENT: {
    CREATE: 'CREATE_DOCUMENT_CONTENT',
    UPDATE: 'UPDATE_DOCUMENT_CONTENT',
    DELETE: 'DELETE_DOCUMENT_CONTENT',
  },
  HOMEWORK_CONTENT: {
    CREATE: 'CREATE_HOMEWORK_CONTENT',
    UPDATE: 'UPDATE_HOMEWORK_CONTENT',
    DELETE: 'DELETE_HOMEWORK_CONTENT',
  },
  HOMEWORK_SUBMIT: {
    CREATE: 'CREATE_HOMEWORK_SUBMIT',
    UPDATE: 'UPDATE_HOMEWORK_SUBMIT',
    DELETE: 'DELETE_HOMEWORK_SUBMIT',
    GRADE: 'GRADE_HOMEWORK_SUBMIT',
  },
  VIDEO_CONTENT: {
    CREATE: 'CREATE_VIDEO_CONTENT',
    UPDATE: 'UPDATE_VIDEO_CONTENT',
    DELETE: 'DELETE_VIDEO_CONTENT',
  },
  YOUTUBE_CONTENT: {
    CREATE: 'CREATE_YOUTUBE_CONTENT',
    UPDATE: 'UPDATE_YOUTUBE_CONTENT',
    DELETE: 'DELETE_YOUTUBE_CONTENT',
  },
  NOTIFICATION: {
    SEND: 'SEND_NOTIFICATION',
    DELETE: 'DELETE_NOTIFICATION',
    MARK_READ: 'MARK_NOTIFICATION_READ',
  },
  TUITION_PAYMENT: {
    CREATE: 'CREATE_TUITION_PAYMENT',
    CREATE_BULK: 'CREATE_BULK_TUITION_PAYMENT',
    UPDATE: 'UPDATE_TUITION_PAYMENT',
    DELETE: 'DELETE_TUITION_PAYMENT',
  },
} as const

// Mapping action to reverse action for rollback
export const ROLLBACK_ACTIONS = {
  // CREATE -> DELETE (xóa record đã tạo)
  CREATE_USER: 'DELETE_USER',
  CREATE_ROLE: 'DELETE_ROLE',
  CREATE_DOCUMENT: 'DELETE_DOCUMENT',
  CREATE_IMAGE: 'DELETE_IMAGE',
  CREATE_SUBJECT: 'DELETE_SUBJECT',
  CREATE_CHAPTER: 'DELETE_CHAPTER',
  CREATE_ATTENDANCE: 'DELETE_ATTENDANCE',
  CREATE_BULK_ATTENDANCE: 'DELETE_ATTENDANCE',
  CREATE_CLASS_SESSION: 'DELETE_CLASS_SESSION',
  CREATE_COURSE: 'DELETE_COURSE',
  CREATE_COURSE_CLASS: 'DELETE_COURSE_CLASS',
  CREATE_COURSE_ENROLLMENT: 'DELETE_COURSE_ENROLLMENT',
  CREATE_LEARNING_ITEM: 'DELETE_LEARNING_ITEM',
  CREATE_DOCUMENT_CONTENT: 'DELETE_DOCUMENT_CONTENT',
  CREATE_HOMEWORK_CONTENT: 'DELETE_HOMEWORK_CONTENT',
  CREATE_HOMEWORK_SUBMIT: 'DELETE_HOMEWORK_SUBMIT',
  CREATE_VIDEO_CONTENT: 'DELETE_VIDEO_CONTENT',
  CREATE_YOUTUBE_CONTENT: 'DELETE_YOUTUBE_CONTENT',
  SEND_NOTIFICATION: 'DELETE_NOTIFICATION',

  // DELETE -> CREATE (tạo lại record đã xóa)
  DELETE_USER: 'CREATE_USER',
  DELETE_ROLE: 'CREATE_ROLE',
  DELETE_DOCUMENT: 'CREATE_DOCUMENT',
  DELETE_IMAGE: 'CREATE_IMAGE',
  DELETE_SUBJECT: 'CREATE_SUBJECT',
  DELETE_CHAPTER: 'CREATE_CHAPTER',
  DELETE_ATTENDANCE: 'CREATE_ATTENDANCE',
  DELETE_CLASS_SESSION: 'CREATE_CLASS_SESSION',
  DELETE_CLASS_STUDENT: 'CREATE_CLASS_STUDENT',
  DELETE_COURSE: 'CREATE_COURSE',
  DELETE_COURSE_CLASS: 'CREATE_COURSE_CLASS',
  DELETE_COURSE_ENROLLMENT: 'CREATE_COURSE_ENROLLMENT',
  DELETE_LEARNING_ITEM: 'CREATE_LEARNING_ITEM',
  DELETE_DOCUMENT_CONTENT: 'CREATE_DOCUMENT_CONTENT',
  DELETE_HOMEWORK_CONTENT: 'CREATE_HOMEWORK_CONTENT',
  DELETE_HOMEWORK_SUBMIT: 'CREATE_HOMEWORK_SUBMIT',
  DELETE_VIDEO_CONTENT: 'CREATE_VIDEO_CONTENT',
  DELETE_YOUTUBE_CONTENT: 'CREATE_YOUTUBE_CONTENT',
  DELETE_NOTIFICATION: 'SEND_NOTIFICATION',

  // UPDATE -> UPDATE (update lại với data cũ)
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_ROLE: 'UPDATE_ROLE',
  UPDATE_DOCUMENT: 'UPDATE_DOCUMENT',
  UPDATE_IMAGE: 'UPDATE_IMAGE',
  UPDATE_SUBJECT: 'UPDATE_SUBJECT',
  UPDATE_CHAPTER: 'UPDATE_CHAPTER',
  UPDATE_ATTENDANCE: 'UPDATE_ATTENDANCE',
  UPDATE_CLASS_SESSION: 'UPDATE_CLASS_SESSION',
  UPDATE_COURSE: 'UPDATE_COURSE',
  UPDATE_COURSE_CLASS: 'UPDATE_COURSE_CLASS',
  UPDATE_COURSE_ENROLLMENT: 'UPDATE_COURSE_ENROLLMENT',
  UPDATE_LEARNING_ITEM: 'UPDATE_LEARNING_ITEM',
  UPDATE_DOCUMENT_CONTENT: 'UPDATE_DOCUMENT_CONTENT',
  UPDATE_HOMEWORK_CONTENT: 'UPDATE_HOMEWORK_CONTENT',
  UPDATE_HOMEWORK_SUBMIT: 'UPDATE_HOMEWORK_SUBMIT',
  GRADE_HOMEWORK_SUBMIT: 'GRADE_HOMEWORK_SUBMIT',
  UPDATE_VIDEO_CONTENT: 'UPDATE_VIDEO_CONTENT',
  UPDATE_YOUTUBE_CONTENT: 'UPDATE_YOUTUBE_CONTENT',
} as const

// Action operation types
export const ACTION_OPERATIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
} as const

// Extract operation from action key
export const getActionOperation = (actionKey: string): string => {
  if (actionKey.startsWith('CREATE_')) return ACTION_OPERATIONS.CREATE
  if (actionKey.startsWith('UPDATE_')) return ACTION_OPERATIONS.UPDATE
  if (actionKey.startsWith('DELETE_')) return ACTION_OPERATIONS.DELETE
  return 'UNKNOWN'
}

// Get reverse action for rollback
export const getRollbackAction = (actionKey: string): string => {
  return ROLLBACK_ACTIONS[actionKey as keyof typeof ROLLBACK_ACTIONS] || actionKey
}

// Check if action is reversible
export const isReversibleAction = (actionKey: string): boolean => {
  return actionKey in ROLLBACK_ACTIONS
}

// Get rollback strategy
export const getRollbackStrategy = (
  actionKey: string,
): {
  operation: string
  reverseAction: string
  strategy: string
} => {
  const operation = getActionOperation(actionKey)
  const reverseAction = getRollbackAction(actionKey)

  let strategy = ''
  switch (operation) {
    case ACTION_OPERATIONS.CREATE:
      strategy = 'Delete the created record'
      break
    case ACTION_OPERATIONS.DELETE:
      strategy = 'Restore the deleted record from beforeData'
      break
    case ACTION_OPERATIONS.UPDATE:
      strategy = 'Revert to previous state from beforeData'
      break
    default:
      strategy = 'Manual rollback required'
  }

  return {
    operation,
    reverseAction,
    strategy,
  }
}

export type ActionKey = string
export type RollbackAction = (typeof ROLLBACK_ACTIONS)[keyof typeof ROLLBACK_ACTIONS]
