export enum ReportReason {
  INCORRECT_TEACHING = 'INCORRECT_TEACHING',
  INCORRECT_CONTENT = 'INCORRECT_CONTENT',
  INAPPROPRIATE_BEHAVIOR = 'INAPPROPRIATE_BEHAVIOR',
  CLASS_ISSUE = 'CLASS_ISSUE',
  TECHNICAL_ISSUE = 'TECHNICAL_ISSUE',
  WEBSITE_ISSUE = 'WEBSITE_ISSUE',
  OTHER = 'OTHER',
}
