// src/application/application.module.ts
import { Module } from '@nestjs/common'
import { InfrastructureModule } from '../infrastructure/infrastructure.module'
import {
  RegisterAdminUseCase,
  RegisterStudentUseCase,
  LoginAdminUseCase,
  LoginStudentUseCase,
  RefreshTokenUseCase,
  LogoutUseCase,
  CreateRoleUseCase,
  RollbackUseCase,
  GetAllStudentUseCase,
  UpdateStudentUseCase,
  UpdateAdminUseCase,
  UpdateUserUseCase,
  UpdateUserAvatarUseCase,
  GoogleOAuthAdminUseCase,
  GoogleOAuthStudentUseCase,
  SendVerificationEmailUseCase,
  VerifyEmailUseCase,
  FetchStudentFromApiUseCase,
  GetProfileStudentUseCase,
  SendResetPasswordEmailUseCase,
  ResetPasswordUseCase,
  UploadMediaUseCase,
  GetMediaListUseCase,
  GetMediaUseCase,
  UpdateMediaUseCase,
  DeleteMediaUseCase,
} from './use-cases'

@Module({
  imports: [InfrastructureModule],
  providers: [
    RegisterAdminUseCase,
    RegisterStudentUseCase,
    LoginAdminUseCase,
    LoginStudentUseCase,
    RefreshTokenUseCase,
    LogoutUseCase,
    CreateRoleUseCase,
    RollbackUseCase,
    GetAllStudentUseCase,
    UpdateStudentUseCase,
    UpdateAdminUseCase,
    UpdateUserUseCase,
    UpdateUserAvatarUseCase,
    GoogleOAuthAdminUseCase,
    GoogleOAuthStudentUseCase,
    SendVerificationEmailUseCase,
    VerifyEmailUseCase,
    FetchStudentFromApiUseCase,
    GetProfileStudentUseCase,
    ResetPasswordUseCase,
    SendResetPasswordEmailUseCase,
    UploadMediaUseCase,
    GetMediaListUseCase,
    GetMediaUseCase,
    UpdateMediaUseCase,
    DeleteMediaUseCase,
  ],
  exports: [
    RegisterAdminUseCase,
    RegisterStudentUseCase,
    LoginAdminUseCase,
    LoginStudentUseCase,
    RefreshTokenUseCase,
    LogoutUseCase,
    CreateRoleUseCase,
    RollbackUseCase,
    GetAllStudentUseCase,
    UpdateStudentUseCase,
    UpdateAdminUseCase,
    UpdateUserUseCase,
    UpdateUserAvatarUseCase,
    GoogleOAuthAdminUseCase,
    GoogleOAuthStudentUseCase,
    SendVerificationEmailUseCase,
    VerifyEmailUseCase,
    FetchStudentFromApiUseCase,
    GetProfileStudentUseCase,
    ResetPasswordUseCase,
    SendResetPasswordEmailUseCase,
    UploadMediaUseCase,
    GetMediaListUseCase,
    GetMediaUseCase,
    UpdateMediaUseCase,
    DeleteMediaUseCase,
  ],
})
export class ApplicationModule { }
