// src/application/application.module.ts
import { Module } from '@nestjs/common'
import { InfrastructureModule } from '../infrastructure/infrastructure.module'
import {
  RegisterAdminUseCase,
  RegisterStudentUseCase,
  LoginAdminUseCase,
  LoginStudentUseCase,
  RefreshTokenUseCase,
  LogoutUseCase,
  CreateRoleUseCase,
  RollbackUseCase,
  GetAuditLogUseCase,
  GetAllAuditLogsUseCase,
  GetAllStudentUseCase,
  CreateStudentUseCase,
  UpdateStudentUseCase,
  UpdateAdminUseCase,
  UpdateUserUseCase,
  UpdateUserAvatarUseCase,
  GoogleOAuthAdminUseCase,
  GoogleOAuthStudentUseCase,
  SendVerificationEmailUseCase,
  VerifyEmailUseCase,
  FetchStudentFromApiUseCase,
  GetProfileStudentUseCase,
  SendResetPasswordEmailUseCase,
  ResetPasswordUseCase,
  UploadMediaUseCase,
  GetMediaListUseCase,
  GetMediaUseCase,
  UpdateMediaUseCase,
  DeleteMediaUseCase,
  GetMediaDownloadUrlUseCase,
  GetMediaViewUrlUseCase,
  GetBucketsListUseCase,
  GetAdminProfileUseCase,
  UpdateAdminProfileUseCase,
  CreatePermissionUseCase,
  GetPermissionUseCase,
  GetAllPermissionsUseCase,
  UpdatePermissionUseCase,
  DeletePermissionUseCase,
  GetRoleUseCase,
  GetAllRolesUseCase,
  UpdateRoleUseCase,
  DeleteRoleUseCase,
  AssignRoleToUserUseCase,
  GetUserRolesUseCase,
  ToggleRolePermissionUseCase,
  GetPermissionGroupsUseCase,
  AttachMediaUseCase,
  DetachMediaUseCase,
  DetachMediaByEntityUseCase,
  GetMediaUsagesByMediaUseCase,
  GetMediaUsagesByEntityUseCase,
  CreateMediaFolderUseCase,
  GetMediaFolderUseCase,
  GetMediaFolderListUseCase,
  GetFolderChildrenUseCase,
  UpdateMediaFolderUseCase,
  DeleteMediaFolderUseCase,
  GetAllAdminUseCase,
  GetAdminByIdUseCase,
  RemoveRoleFromUserUseCase
} from './use-cases'
import {
  GetAllCourseUseCase,
  GetCourseByIdUseCase,
  CreateCourseUseCase,
  UpdateCourseUseCase,
  DeleteCourseUseCase,
} from './use-cases/course'
import {
  GetAllCourseClassUseCase,
  GetCourseClassByIdUseCase,
  CreateCourseClassUseCase,
  UpdateCourseClassUseCase,
  DeleteCourseClassUseCase,
} from './use-cases/course-class'
import {
  GetAllClassSessionUseCase,
  GetClassSessionByIdUseCase,
  CreateClassSessionUseCase,
  UpdateClassSessionUseCase,
  DeleteClassSessionUseCase,
} from './use-cases/class-session'
import {
  GetAllClassStudentUseCase,
  CreateClassStudentUseCase,
  DeleteClassStudentUseCase,
} from './use-cases/class-student'
import {
  GetAllCourseEnrollmentUseCase,
  GetCourseEnrollmentByIdUseCase,
  CreateCourseEnrollmentUseCase,
  UpdateCourseEnrollmentUseCase,
  DeleteCourseEnrollmentUseCase,
} from './use-cases/course-enrollment'

@Module({
  imports: [InfrastructureModule],
  providers: [
    RegisterAdminUseCase,
    RegisterStudentUseCase,
    LoginAdminUseCase,
    LoginStudentUseCase,
    RefreshTokenUseCase,
    LogoutUseCase,
    RollbackUseCase,
    GetAuditLogUseCase,
    GetAllAuditLogsUseCase,
    GetAllStudentUseCase,
    CreateStudentUseCase,
    UpdateStudentUseCase,
    UpdateAdminUseCase,
    UpdateUserUseCase,
    UpdateUserAvatarUseCase,
    GoogleOAuthAdminUseCase,
    GoogleOAuthStudentUseCase,
    SendVerificationEmailUseCase,
    VerifyEmailUseCase,
    FetchStudentFromApiUseCase,
    GetProfileStudentUseCase,
    ResetPasswordUseCase,
    SendResetPasswordEmailUseCase,
    UploadMediaUseCase,
    GetMediaListUseCase,
    GetMediaUseCase,
    UpdateMediaUseCase,
    DeleteMediaUseCase,
    GetMediaDownloadUrlUseCase,
    GetMediaViewUrlUseCase,
    GetAdminProfileUseCase,
    UpdateAdminProfileUseCase,
    CreatePermissionUseCase,
    GetPermissionUseCase,
    GetAllPermissionsUseCase,
    UpdatePermissionUseCase,
    DeletePermissionUseCase,
    CreateRoleUseCase,
    GetRoleUseCase,
    GetAllRolesUseCase,
    UpdateRoleUseCase,
    DeleteRoleUseCase,
    AssignRoleToUserUseCase,
    GetUserRolesUseCase,
    ToggleRolePermissionUseCase,
    GetPermissionGroupsUseCase,
    AttachMediaUseCase,
    DetachMediaUseCase,
    DetachMediaByEntityUseCase,
    GetMediaUsagesByMediaUseCase,
    GetMediaUsagesByEntityUseCase,
    CreateMediaFolderUseCase,
    GetMediaFolderUseCase,
    GetMediaFolderListUseCase,
    GetFolderChildrenUseCase,
    UpdateMediaFolderUseCase,
    DeleteMediaFolderUseCase,
    GetBucketsListUseCase,
    GetAllAdminUseCase,
    GetAdminByIdUseCase,
    RemoveRoleFromUserUseCase,
    // Course use-cases
    GetAllCourseUseCase,
    GetCourseByIdUseCase,
    CreateCourseUseCase,
    UpdateCourseUseCase,
    DeleteCourseUseCase,
    // CourseClass use-cases
    GetAllCourseClassUseCase,
    GetCourseClassByIdUseCase,
    CreateCourseClassUseCase,
    UpdateCourseClassUseCase,
    DeleteCourseClassUseCase,
    // ClassSession use-cases
    GetAllClassSessionUseCase,
    GetClassSessionByIdUseCase,
    CreateClassSessionUseCase,
    UpdateClassSessionUseCase,
    DeleteClassSessionUseCase,
    // ClassStudent use-cases
    GetAllClassStudentUseCase,
    CreateClassStudentUseCase,
    DeleteClassStudentUseCase,
    // CourseEnrollment use-cases
    GetAllCourseEnrollmentUseCase,
    GetCourseEnrollmentByIdUseCase,
    CreateCourseEnrollmentUseCase,
    UpdateCourseEnrollmentUseCase,
    DeleteCourseEnrollmentUseCase,
  ],
  exports: [
    RegisterAdminUseCase,
    RegisterStudentUseCase,
    LoginAdminUseCase,
    LoginStudentUseCase,
    RefreshTokenUseCase,
    LogoutUseCase,
    CreateRoleUseCase,
    RollbackUseCase,
    GetAuditLogUseCase,
    GetAllAuditLogsUseCase,
    GetAllStudentUseCase,
    CreateStudentUseCase,
    UpdateStudentUseCase,
    UpdateAdminUseCase,
    UpdateUserUseCase,
    UpdateUserAvatarUseCase,
    GoogleOAuthAdminUseCase,
    GoogleOAuthStudentUseCase,
    SendVerificationEmailUseCase,
    VerifyEmailUseCase,
    FetchStudentFromApiUseCase,
    GetProfileStudentUseCase,
    ResetPasswordUseCase,
    SendResetPasswordEmailUseCase,
    UploadMediaUseCase,
    GetMediaListUseCase,
    GetMediaUseCase,
    UpdateMediaUseCase,
    DeleteMediaUseCase,
    GetMediaDownloadUrlUseCase,
    GetMediaViewUrlUseCase,
    GetBucketsListUseCase,
    GetAdminProfileUseCase,
    UpdateAdminProfileUseCase,
    CreatePermissionUseCase,
    GetPermissionUseCase,
    GetAllPermissionsUseCase,
    UpdatePermissionUseCase,
    DeletePermissionUseCase,
    CreateRoleUseCase,
    GetRoleUseCase,
    GetAllRolesUseCase,
    UpdateRoleUseCase,
    DeleteRoleUseCase,
    AssignRoleToUserUseCase,
    GetUserRolesUseCase,
    ToggleRolePermissionUseCase,
    GetPermissionGroupsUseCase,
    AttachMediaUseCase,
    DetachMediaUseCase,
    DetachMediaByEntityUseCase,
    GetMediaUsagesByMediaUseCase,
    GetMediaUsagesByEntityUseCase,
    CreateMediaFolderUseCase,
    GetMediaFolderUseCase,
    GetMediaFolderListUseCase,
    GetFolderChildrenUseCase,
    UpdateMediaFolderUseCase,
    DeleteMediaFolderUseCase,
    GetAllAdminUseCase,
    GetAdminByIdUseCase,
    RemoveRoleFromUserUseCase,
    // Course use-cases
    GetAllCourseUseCase,
    GetCourseByIdUseCase,
    CreateCourseUseCase,
    UpdateCourseUseCase,
    DeleteCourseUseCase,
    // CourseClass use-cases
    GetAllCourseClassUseCase,
    GetCourseClassByIdUseCase,
    CreateCourseClassUseCase,
    UpdateCourseClassUseCase,
    DeleteCourseClassUseCase,
    // ClassSession use-cases
    GetAllClassSessionUseCase,
    GetClassSessionByIdUseCase,
    CreateClassSessionUseCase,
    UpdateClassSessionUseCase,
    DeleteClassSessionUseCase,
    // ClassStudent use-cases
    GetAllClassStudentUseCase,
    CreateClassStudentUseCase,
    DeleteClassStudentUseCase,
    // CourseEnrollment use-cases
    GetAllCourseEnrollmentUseCase,
    GetCourseEnrollmentByIdUseCase,
    CreateCourseEnrollmentUseCase,
    UpdateCourseEnrollmentUseCase,
    DeleteCourseEnrollmentUseCase,
  ],
})
export class ApplicationModule { }
